# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class PortRegistry < Formula
  desc "Local port registry to prevent Docker port conflicts"
  homepage "https://github.com/n3r/port-registry"
  version "0.1.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/n3r/port-registry/releases/download/v0.1.0/port-registry_0.1.0_darwin_amd64.tar.gz"
      sha256 "492f014e5ec811a54f8c2579df3f9d0b7c1b6288cfae63437d94588df75538f2"

      def install
        bin.install "port-server"
        bin.install "portctl"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/n3r/port-registry/releases/download/v0.1.0/port-registry_0.1.0_darwin_arm64.tar.gz"
      sha256 "905b826d2bf1f18ebfd4b991a1e15dd5ddf875e83fc23fa9249264781b3c4b6f"

      def install
        bin.install "port-server"
        bin.install "portctl"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/n3r/port-registry/releases/download/v0.1.0/port-registry_0.1.0_linux_amd64.tar.gz"
      sha256 "791355ef64ad245f0cf8f227153459f4a11468f8c90fcf20f0f1d8bd4f7aa00a"
      def install
        bin.install "port-server"
        bin.install "portctl"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/n3r/port-registry/releases/download/v0.1.0/port-registry_0.1.0_linux_arm64.tar.gz"
      sha256 "da903eb5c221bd0038eb9b3d1c9fc1767b4486c600456bfcdf62dabb59ab8d11"
      def install
        bin.install "port-server"
        bin.install "portctl"
      end
    end
  end

  test do
    system bin/"portctl", "version"
  end
end
