# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class PortRegistry < Formula
  desc "Local port registry to prevent Docker port conflicts"
  homepage "https://github.com/n3r/port-registry"
  version "0.3.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/n3r/port-registry/releases/download/v0.3.0/port-registry_0.3.0_darwin_amd64.tar.gz"
      sha256 "a24ce66aa09b69c4f1aa8e066ef473c293b0f51a99b9785c70dac7e9f655e9b7"

      def install
        bin.install "port-registry"
        bin.install "portctl"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/n3r/port-registry/releases/download/v0.3.0/port-registry_0.3.0_darwin_arm64.tar.gz"
      sha256 "b6ca6cd310c0ce2f689e72772d9ddb5603bcd0a1c3b67aa7bc4d30ca9c1af204"

      def install
        bin.install "port-registry"
        bin.install "portctl"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/n3r/port-registry/releases/download/v0.3.0/port-registry_0.3.0_linux_amd64.tar.gz"
      sha256 "265b5fbd22a0671a9c121b4ac5cc74a59d70a39b5175af1531a46a815c5e0532"
      def install
        bin.install "port-registry"
        bin.install "portctl"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/n3r/port-registry/releases/download/v0.3.0/port-registry_0.3.0_linux_arm64.tar.gz"
      sha256 "514d3324a9d13155341b636ff1115e5a3aaaef37bb29eb08797f49e5aa75f70a"
      def install
        bin.install "port-registry"
        bin.install "portctl"
      end
    end
  end

  test do
    system bin/"portctl", "version"
  end
end
